name: Mover imágenes a la carpeta /images

on:
  push:
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.gif'
      - '**.webp'

jobs:
  organizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Crear carpeta /images si no existe
        run: mkdir -p images

      - name: Mover imágenes a /images
        run: |
          shopt -s globstar nullglob
          for ext in jpg jpeg png gif webp; do
            for img in **/*.${ext}; do
              # Evitar mover imágenes que ya estén en /images
              if [[ "$img" != images/* ]]; then
                mv "$img" images/
                echo "Movida: $img → images/"
              fi
            done
          done

      - name: Hacer commit de los cambios
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add images
          git add -u
          git commit -m "Movidas imágenes a la carpeta /images" || echo "No hay cambios"
          git push
